- hosts: localhost
  tasks:

  - name: Login Openshift Destino
    shell: "oc login --token={{ TOKEN_API_DESTINO }} --server={{ ENDERECO_API_DESTINO }} --insecure-skip-tls-verify=true"
  - name: "Cria namespace {{ NAMESPACE }}"
    shell: "oc new-project {{ NAMESPACE }}"
    ignore_errors: yes
  - name: Deploy App
    shell: "oc new-app --image-stream=php https://github.com/LucianoRed/phpapp2.git --name=phpapp2 -e CLOUD={{ CLOUD }} -n {{ NAMESPACE }}"
    ignore_errors: yes
  - name: Expoe rota
    shell: "oc expose service/phpapp2 -n {{ NAMESPACE }}"
    ignore_errors: yes
  - name: Expoe rota 2
    shell: "oc expose service/phpapp2 --hostname=techu.openshiftdemo.com.br --name=rota2 -n {{ NAMESPACE }}"
    ignore_errors: yes    
  - name: Obtem Rota
    shell: "oc get route phpapp2 -n {{ NAMESPACE }} | awk {'print $2'}  | grep -v HOST"
    register: resultado
    ignore_errors: yes
  - name: "Altera DNS CloudFlare com valor {{ resultado.stdout }}"
    community.general.cloudflare_dns:
      zone: openshiftdemo.com.br
      record: techu
      type: CNAME
      value: "{{ resultado.stdout }}"
      account_api_key: "{{ API_CLOUDFLARE }}"
      api_token: "{{ TOKEN_CLOUDFLARE }}"
      ttl: 120
      # account_email: "{{ EMAIL_CLOUDFLARE }}"
    ignore_errors: yes


# Remove app do destino

  - name: Login Openshift Destino
    shell: "oc login --token={{ TOKEN_API_ORIGEM }} --server={{ ENDERECO_API_ORIGEM }}  --insecure-skip-tls-verify=true"
    ignore_errors: yes
  - name: Remove Deployment
    shell: "oc delete all -l app=phpapp2 -n {{ NAMESPACE }}"
    ignore_errors: yes
  - name: "Remove namespace {{ NAMESPACE }}"
    shell: "oc delete project {{ NAMESPACE }}"
    ignore_errors: yes


