apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/LucianoRed/phpapp2.git
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"phpapp-2-git:latest","namespace":"phpapp"},"fieldPath":"spec.template.spec.containers[?(@.name==\"phpapp-2-git\")].image","pause":"false"}]'
    openshift.io/generated-by: OpenShiftWebConsole
  generation: 2
  labels:
    app: phpapp-2-git
    app.kubernetes.io/component: phpapp-2-git
    app.kubernetes.io/instance: phpapp-2-git
    app.kubernetes.io/name: phpapp-2-git
    app.kubernetes.io/part-of: phpapp-2-git-app
    app.openshift.io/runtime: php
    app.openshift.io/runtime-version: 7.4-ubi8
  name: phpapp-2-git
  namespace: techu-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: phpapp-2-git
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpapp-2-git
        deploymentconfig: phpapp-2-git
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/phpapp/phpapp-2-git
        imagePullPolicy: Always
        name: phpapp-2-git
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30